Define vertex shader inline to add #version
new_default_vertex assumes a version of None and adds the
ES | COMPATIBILITY profile, making it incompatible with our fragment
shader.

    ERROR               glshader gstglshader.c:705:gst_gl_shader_link: Shader linking failed:
    error: all shaders must use same shading language version